# Generated by Django 5.1.15 on 2026-09-14 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='orders.order'),
        ),
        migrations.AddField(
            model_name='deliveryboyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryearning',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='delivery.deliveryassignment'),
        ),
        migrations.AddField(
            model_name='deliveryearning',
            name='delivery_boy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_earnings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryearning',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earnings', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='deliveryearning',
            index=models.Index(fields=['delivery_boy', 'created_at'], name='delivery_de_deliver_a011a6_idx'),
        ),
    ]
